{
  imports = [
    ./aseprite.nix
    ./hyprland
    ./cava.nix
    ./chromium.nix
    ./cosmic-files.nix
    ./discord
    ./dunst.nix
    ./firefox.nix
    ./ghostty.nix
    ./niri
    ./obsidian.nix
    ./quickshell.nix
    ./satty.nix
    ./spotify.nix
    ./wezterm
    ./zed.nix
    ./zen-browser.nix
  ];
}
