keys:
  - &isabel age1w98qzycsw5jk9hpy4yg5ld05qqdvs2vxctdypx0tqppvxrk579yshzctus
  - &robin age15sejxcynw44vgsee5znxvq7vtuust686wn4f3u0upp42zay6ugqqp5lvv8

  - &minerva age1e8wknnpexn86qrac3lrsgd4kce33t9t6sa54x9u5duplhjkra5ns3g7kn9
  - &skadi age1hmrh866kwqar3p7sdmvjfulpn4956x3d5s4x50cgg9256jlad46skqyu5f
  - &hestia age1g4ku5x489s5wrwjewnsahl4x09mwn4000z4j8nj43h8443t52yrse0e9mg
  - &athena age1dfcv3m85krzqya9tsft5hwrapl3zq35ry6zrt8gy92afcyrrau6q879rfc

creation_rules:
  - path_regex: secrets/isabel\.yaml
    key_groups:
      - age:
        - *isabel

  - path_regex: secrets/robin\.yaml
    key_groups:
      - age:
        - *robin

  - path_regex: secrets/services/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *isabel
        - *minerva
        - *skadi
        - *hestia
        - *athena
