keys:
  - &isabel ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMQDiHbMSinj8twL9cTgPOfI6OMexrTZyHX27T8gnMj2
  - &robin age15sejxcynw44vgsee5znxvq7vtuust686wn4f3u0upp42zay6ugqqp5lvv8

  - &minerva ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAomF8O3ZqZBpLRlAkS1+FwRllSMrREHtndw07trrfcA
  - &skadi ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKV3N2r1cX3kZMHxuJYaFsjWJRtik/2b/KZ5ru38IqAT
  - &hestia ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINy5ZskGK7y0G6/Fiuq6yHGVyZVrePeND+sH/bOYGQqb
  - &athena age1dfcv3m85krzqya9tsft5hwrapl3zq35ry6zrt8gy92afcyrrau6q879rfc

creation_rules:
  - path_regex: secrets/isabel\.yaml
    key_groups:
      - age:
        - *isabel

  - path_regex: secrets/robin\.yaml
    key_groups:
      - age:
        - *robin

  - path_regex: secrets/services/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *isabel
        - *minerva
        - *skadi
        - *hestia
        - *athena
