[book]
authors = ["isabel roses", "Robin Roses"]
language = "en"
multilingual = false
src = "src"
title = "dotfiles"

[build]
build-dir = "./dist"
create-missing = false

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
git-repository-url = "https://github.com/isabelroses/dotfiles"
git-repository-icon = "fa-code-fork"
cname = "dotfiles.isabelroses.com"
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-alerts.css"]

[preprocessor.alerts]
